// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { BreedsListHandlerData, BreedsListHandlerErrors, BreedsListHandlerResponses, CatDetailHandlerData, CatDetailHandlerErrors, CatDetailHandlerResponses, CatRolesListHandlerData, CatRolesListHandlerErrors, CatRolesListHandlerResponses, CatSessionProfileHandlerData, CatSessionProfileHandlerErrors, CatSessionProfileHandlerResponses, CatUpdateProfileHandlerData, CatUpdateProfileHandlerErrors, CatUpdateProfileHandlerResponses, MatchAddUpdateHandlerData, MatchAddUpdateHandlerErrors, MatchAddUpdateHandlerResponses, MatchesListHandlerData, MatchesListHandlerErrors, MatchesListHandlerResponses, MatchSuggestionsHandlerData, MatchSuggestionsHandlerErrors, MatchSuggestionsHandlerResponses, SessionGetFromCookieHandlerData, SessionGetFromCookieHandlerErrors, SessionGetFromCookieHandlerResponses, SignInHandlerData, SignInHandlerErrors, SignInHandlerResponses, SignUpHandlerData, SignUpHandlerErrors, SignUpHandlerResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const signInHandler = <ThrowOnError extends boolean = false>(options: Options<SignInHandlerData, ThrowOnError>) => (options.client ?? client).post<SignInHandlerResponses, SignInHandlerErrors, ThrowOnError>({
    url: '/api/v1/auth/sign-in',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const signUpHandler = <ThrowOnError extends boolean = false>(options: Options<SignUpHandlerData, ThrowOnError>) => (options.client ?? client).post<SignUpHandlerResponses, SignUpHandlerErrors, ThrowOnError>({
    url: '/api/v1/auth/sign-up',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const breedsListHandler = <ThrowOnError extends boolean = false>(options?: Options<BreedsListHandlerData, ThrowOnError>) => (options?.client ?? client).get<BreedsListHandlerResponses, BreedsListHandlerErrors, ThrowOnError>({ url: '/api/v1/breeds', ...options });

export const catDetailHandler = <ThrowOnError extends boolean = false>(options: Options<CatDetailHandlerData, ThrowOnError>) => (options.client ?? client).get<CatDetailHandlerResponses, CatDetailHandlerErrors, ThrowOnError>({ url: '/api/v1/cats/{id}', ...options });

export const matchesListHandler = <ThrowOnError extends boolean = false>(options?: Options<MatchesListHandlerData, ThrowOnError>) => (options?.client ?? client).get<MatchesListHandlerResponses, MatchesListHandlerErrors, ThrowOnError>({ url: '/api/v1/matches', ...options });

export const matchAddUpdateHandler = <ThrowOnError extends boolean = false>(options: Options<MatchAddUpdateHandlerData, ThrowOnError>) => (options.client ?? client).post<MatchAddUpdateHandlerResponses, MatchAddUpdateHandlerErrors, ThrowOnError>({
    url: '/api/v1/matches',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const matchSuggestionsHandler = <ThrowOnError extends boolean = false>(options?: Options<MatchSuggestionsHandlerData, ThrowOnError>) => (options?.client ?? client).get<MatchSuggestionsHandlerResponses, MatchSuggestionsHandlerErrors, ThrowOnError>({ url: '/api/v1/matches/suggestions', ...options });

export const catSessionProfileHandler = <ThrowOnError extends boolean = false>(options?: Options<CatSessionProfileHandlerData, ThrowOnError>) => (options?.client ?? client).get<CatSessionProfileHandlerResponses, CatSessionProfileHandlerErrors, ThrowOnError>({ url: '/api/v1/profile', ...options });

export const catUpdateProfileHandler = <ThrowOnError extends boolean = false>(options?: Options<CatUpdateProfileHandlerData, ThrowOnError>) => (options?.client ?? client).put<CatUpdateProfileHandlerResponses, CatUpdateProfileHandlerErrors, ThrowOnError>({ url: '/api/v1/profile', ...options });

export const catRolesListHandler = <ThrowOnError extends boolean = false>(options?: Options<CatRolesListHandlerData, ThrowOnError>) => (options?.client ?? client).get<CatRolesListHandlerResponses, CatRolesListHandlerErrors, ThrowOnError>({ url: '/api/v1/roles', ...options });

export const sessionGetFromCookieHandler = <ThrowOnError extends boolean = false>(options?: Options<SessionGetFromCookieHandlerData, ThrowOnError>) => (options?.client ?? client).get<SessionGetFromCookieHandlerResponses, SessionGetFromCookieHandlerErrors, ThrowOnError>({ url: '/api/v1/session', ...options });
