// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CatDetailHandlerData, CatDetailHandlerErrors, CatDetailHandlerResponses, CatsListHandlerData, CatsListHandlerErrors, CatsListHandlerResponses, MatchesListHandlerData, MatchesListHandlerErrors, MatchesListHandlerResponses, MatchSuggestionsHandlerData, MatchSuggestionsHandlerErrors, MatchSuggestionsHandlerResponses, SessionGetByIdHandlerData, SessionGetByIdHandlerErrors, SessionGetByIdHandlerResponses, SignInHandlerData, SignInHandlerErrors, SignInHandlerResponses, SignUpHandlerData, SignUpHandlerErrors, SignUpHandlerResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const signInHandler = <ThrowOnError extends boolean = false>(options: Options<SignInHandlerData, ThrowOnError>) => (options.client ?? client).post<SignInHandlerResponses, SignInHandlerErrors, ThrowOnError>({
    url: '/api/v1/auth/sign-in',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const signUpHandler = <ThrowOnError extends boolean = false>(options: Options<SignUpHandlerData, ThrowOnError>) => (options.client ?? client).post<SignUpHandlerResponses, SignUpHandlerErrors, ThrowOnError>({
    url: '/api/v1/auth/sign-up',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const catsListHandler = <ThrowOnError extends boolean = false>(options?: Options<CatsListHandlerData, ThrowOnError>) => (options?.client ?? client).get<CatsListHandlerResponses, CatsListHandlerErrors, ThrowOnError>({ url: '/api/v1/cats', ...options });

export const catDetailHandler = <ThrowOnError extends boolean = false>(options: Options<CatDetailHandlerData, ThrowOnError>) => (options.client ?? client).get<CatDetailHandlerResponses, CatDetailHandlerErrors, ThrowOnError>({ url: '/api/v1/cats/{id}', ...options });

export const matchesListHandler = <ThrowOnError extends boolean = false>(options?: Options<MatchesListHandlerData, ThrowOnError>) => (options?.client ?? client).get<MatchesListHandlerResponses, MatchesListHandlerErrors, ThrowOnError>({ url: '/api/v1/matches', ...options });

export const matchSuggestionsHandler = <ThrowOnError extends boolean = false>(options?: Options<MatchSuggestionsHandlerData, ThrowOnError>) => (options?.client ?? client).get<MatchSuggestionsHandlerResponses, MatchSuggestionsHandlerErrors, ThrowOnError>({ url: '/api/v1/matches/suggestions', ...options });

export const sessionGetByIdHandler = <ThrowOnError extends boolean = false>(options: Options<SessionGetByIdHandlerData, ThrowOnError>) => (options.client ?? client).get<SessionGetByIdHandlerResponses, SessionGetByIdHandlerErrors, ThrowOnError>({ url: '/api/v1/session/{id}', ...options });
