// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AuthSignInPayload = {
    name: string;
    password: string;
};

export type AuthSignInResponse = {
    message: string;
    status: Status;
};

export type AuthSignUpPayload = {
    cat: NewCat;
};

export type AuthSignUpResponse = {
    message: string;
    results?: null | AuthSignUpResponseResults;
    status: Status;
};

export type AuthSignUpResponseResults = {
    cat: Cat;
    session_id: string;
};

export type Breed = {
    id: string;
    name: string;
};

export type BreedsListResponse = {
    results: Array<Breed>;
    status: Status;
};

export type Cat = {
    active?: boolean | null;
    age?: number | null;
    avatarFilename?: string | null;
    biography?: string | null;
    birthDate?: string | null;
    breedId?: string | null;
    breedName?: string | null;
    createdAt?: string | null;
    id: string;
    interests: Array<Interest>;
    lastSeen?: string | null;
    name: string;
    photos: Array<CatPhoto>;
    updatedAt?: string | null;
};

export type CatDetailResponse = {
    message?: string | null;
    results?: null | Cat;
    status: Status;
};

export type CatPhoto = {
    altText?: string | null;
    createdAt?: string | null;
    filename: string;
    height?: number | null;
    id: string;
    order?: number | null;
    width?: number | null;
};

export type Interest = {
    id: string;
    name: string;
};

export type Match = {
    id: string;
    initiator_id: string;
    status?: null | MatchStatus;
    target_id: string;
};

export type MatchAddRequest = {
    initiator_id: string;
    status: MatchStatus;
    target_id: string;
};

export type MatchAddedResponse = {
    message: string;
    status: Status;
};

export enum MatchStatus {
    PENDING = 'Pending',
    ACCEPTED = 'Accepted',
    DECLINED = 'Declined'
}

export type MatchSuggestionsResponse = {
    results: Array<Cat>;
    status: Status;
};

export type MatchesListResponse = {
    results: Array<Match>;
    status: Status;
};

export type NewCat = {
    birth_date?: string | null;
    breed_id: string;
    name: string;
    password: string;
};

export enum Status {
    OK = 'OK',
    ERROR = 'ERROR'
}

export type SignInHandlerData = {
    body: AuthSignInPayload;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sign-in';
};

export type SignInHandlerErrors = {
    /**
     * Internal server error
     */
    500: AuthSignInResponse;
};

export type SignInHandlerError = SignInHandlerErrors[keyof SignInHandlerErrors];

export type SignInHandlerResponses = {
    /**
     * Auth sign in
     */
    200: AuthSignInResponse;
};

export type SignInHandlerResponse = SignInHandlerResponses[keyof SignInHandlerResponses];

export type SignUpHandlerData = {
    body: AuthSignUpPayload;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sign-up';
};

export type SignUpHandlerErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type SignUpHandlerResponses = {
    /**
     * Auth sign up
     */
    200: AuthSignUpResponse;
};

export type SignUpHandlerResponse = SignUpHandlerResponses[keyof SignUpHandlerResponses];

export type BreedsListHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/breeds';
};

export type BreedsListHandlerErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type BreedsListHandlerResponses = {
    /**
     * List of all cat breeds
     */
    200: BreedsListResponse;
};

export type BreedsListHandlerResponse = BreedsListHandlerResponses[keyof BreedsListHandlerResponses];

export type CatDetailHandlerData = {
    body?: never;
    path: {
        /**
         * Cat ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/cats/{id}';
};

export type CatDetailHandlerErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type CatDetailHandlerResponses = {
    /**
     * Details for a specific cat
     */
    200: CatDetailResponse;
};

export type CatDetailHandlerResponse = CatDetailHandlerResponses[keyof CatDetailHandlerResponses];

export type MatchesListHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/matches';
};

export type MatchesListHandlerErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type MatchesListHandlerResponses = {
    /**
     * List of all matches for a specific cat
     */
    200: MatchesListResponse;
};

export type MatchesListHandlerResponse = MatchesListHandlerResponses[keyof MatchesListHandlerResponses];

export type MatchAddUpdateHandlerData = {
    body: MatchAddRequest;
    path?: never;
    query?: never;
    url: '/api/v1/matches';
};

export type MatchAddUpdateHandlerErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type MatchAddUpdateHandlerResponses = {
    /**
     * Match created
     */
    201: MatchAddedResponse;
};

export type MatchAddUpdateHandlerResponse = MatchAddUpdateHandlerResponses[keyof MatchAddUpdateHandlerResponses];

export type MatchSuggestionsHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/matches/suggestions';
};

export type MatchSuggestionsHandlerErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type MatchSuggestionsHandlerResponses = {
    /**
     * List of match suggestions for a specific cat
     */
    200: MatchSuggestionsResponse;
};

export type MatchSuggestionsHandlerResponse = MatchSuggestionsHandlerResponses[keyof MatchSuggestionsHandlerResponses];

export type SessionGetFromCookieHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/session';
};

export type SessionGetFromCookieHandlerErrors = {
    /**
     * Session not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type SessionGetFromCookieHandlerResponses = {
    /**
     * Session for current user
     */
    200: CatDetailResponse;
};

export type SessionGetFromCookieHandlerResponse = SessionGetFromCookieHandlerResponses[keyof SessionGetFromCookieHandlerResponses];
