// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AuthSignInPayload = {
    name: string;
    password: string;
};

export type AuthSignInResponse = {
    message: string;
    status: Status;
};

export type AuthSignUpPayload = {
    cat: NewCat;
};

export type AuthSignUpResponse = {
    message: string;
    results?: null | AuthSignUpResponseResults;
    status: Status;
};

export type AuthSignUpResponseResults = {
    cat: Cat;
    session_id: string;
};

export type Cat = {
    active?: boolean | null;
    age?: number | null;
    avatarFilename?: string | null;
    biography?: string | null;
    breedId?: string | null;
    breedName?: string | null;
    createdAt?: string | null;
    id: string;
    interests: Array<Interest>;
    name: string;
    updatedAt?: string | null;
};

export type CatDetailResponse = {
    message?: string | null;
    results?: null | Cat;
    status: Status;
};

export type CatsListResponse = {
    results: Array<Cat>;
    status: string;
};

export type Interest = {
    id: string;
    name: string;
};

export type Match = {
    id: string;
    initiator_id: string;
    status: MatchStatus;
    target_id: string;
};

export enum MatchStatus {
    PENDING = 'Pending',
    ACCEPTED = 'Accepted',
    DECLINED = 'Declined'
}

export type MatchSuggestionsResponse = {
    results: Array<Cat>;
    status: string;
};

export type MatchesListResponse = {
    results: Array<Match>;
    status: string;
};

export type NewCat = {
    age?: number | null;
    breed_id: string;
    name: string;
    password: string;
};

export enum Status {
    OK = 'OK',
    ERROR = 'ERROR'
}

export type SignInHandlerData = {
    body: AuthSignInPayload;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sign-in';
};

export type SignInHandlerErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type SignInHandlerResponses = {
    /**
     * Auth sign in
     */
    200: AuthSignInResponse;
};

export type SignInHandlerResponse = SignInHandlerResponses[keyof SignInHandlerResponses];

export type SignUpHandlerData = {
    body: AuthSignUpPayload;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sign-up';
};

export type SignUpHandlerErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type SignUpHandlerResponses = {
    /**
     * Auth sign up
     */
    200: AuthSignUpResponse;
};

export type SignUpHandlerResponse = SignUpHandlerResponses[keyof SignUpHandlerResponses];

export type CatsListHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/cats';
};

export type CatsListHandlerErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type CatsListHandlerResponses = {
    /**
     * List of cats
     */
    200: CatsListResponse;
};

export type CatsListHandlerResponse = CatsListHandlerResponses[keyof CatsListHandlerResponses];

export type CatDetailHandlerData = {
    body?: never;
    path: {
        /**
         * Cat ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/cats/{id}';
};

export type CatDetailHandlerErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type CatDetailHandlerResponses = {
    /**
     * Details for a specific cat
     */
    200: CatDetailResponse;
};

export type CatDetailHandlerResponse = CatDetailHandlerResponses[keyof CatDetailHandlerResponses];

export type MatchesListHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/matches';
};

export type MatchesListHandlerErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type MatchesListHandlerResponses = {
    /**
     * List of all matches for a specific cat
     */
    200: MatchesListResponse;
};

export type MatchesListHandlerResponse = MatchesListHandlerResponses[keyof MatchesListHandlerResponses];

export type MatchSuggestionsHandlerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/matches/suggestions';
};

export type MatchSuggestionsHandlerErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type MatchSuggestionsHandlerResponses = {
    /**
     * List of match suggestions for a specific cat
     */
    200: MatchSuggestionsResponse;
};

export type MatchSuggestionsHandlerResponse = MatchSuggestionsHandlerResponses[keyof MatchSuggestionsHandlerResponses];

export type SessionGetByIdHandlerData = {
    body?: never;
    path: {
        /**
         * Session id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/session/{id}';
};

export type SessionGetByIdHandlerErrors = {
    /**
     * Internal server error
     */
    500: unknown;
};

export type SessionGetByIdHandlerResponses = {
    /**
     * Details for a specific cat
     */
    200: CatDetailResponse;
};

export type SessionGetByIdHandlerResponse = SessionGetByIdHandlerResponses[keyof SessionGetByIdHandlerResponses];
