// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zAuthSignInPayload = z.object({
    name: z.string(),
    password: z.string()
});

export const zBreed = z.object({
    id: z.uuid(),
    name: z.string()
});

export const zCatPhoto = z.object({
    altText: z.string().nullish(),
    createdAt: z.iso.datetime().nullish(),
    filename: z.string(),
    height: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    id: z.uuid(),
    order: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    width: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish()
});

export const zInterest = z.object({
    id: z.uuid(),
    name: z.string()
});

export const zCat = z.object({
    active: z.boolean().nullish(),
    age: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    avatarFilename: z.string().nullish(),
    biography: z.string().nullish(),
    birthDate: z.iso.datetime().nullish(),
    breedId: z.uuid().nullish(),
    breedName: z.string().nullish(),
    createdAt: z.iso.datetime().nullish(),
    id: z.uuid(),
    interests: z.array(zInterest),
    lastSeen: z.iso.datetime().nullish(),
    name: z.string(),
    photos: z.array(zCatPhoto),
    updatedAt: z.iso.datetime().nullish()
});

export const zAuthSignUpResponseResults = z.object({
    cat: zCat,
    session_id: z.string()
});

export const zMatchStatus = z.enum([
    'Pending',
    'Accepted',
    'Declined'
]);

export const zMatch = z.object({
    id: z.uuid(),
    initiator_id: z.uuid(),
    status: zMatchStatus.nullish(),
    target_id: z.uuid()
});

export const zMatchAddRequest = z.object({
    initiator_id: z.uuid(),
    status: zMatchStatus,
    target_id: z.uuid()
});

export const zNewCat = z.object({
    birth_date: z.iso.datetime().nullish(),
    breed_id: z.uuid(),
    name: z.string(),
    password: z.string()
});

export const zAuthSignUpPayload = z.object({
    cat: zNewCat
});

export const zStatus = z.enum(['OK', 'ERROR']);

export const zAuthSignInResponse = z.object({
    message: z.string(),
    status: zStatus
});

export const zAuthSignUpResponse = z.object({
    message: z.string(),
    results: zAuthSignUpResponseResults.nullish(),
    status: zStatus
});

export const zBreedsListResponse = z.object({
    results: z.array(zBreed),
    status: zStatus
});

export const zCatDetailResponse = z.object({
    message: z.string().nullish(),
    results: zCat.nullish(),
    status: zStatus
});

export const zMatchAddedResponse = z.object({
    message: z.string(),
    status: zStatus
});

export const zMatchSuggestionsResponse = z.object({
    results: z.array(zCat),
    status: zStatus
});

export const zMatchesListResponse = z.object({
    results: z.array(zMatch),
    status: zStatus
});

export const zSignInHandlerData = z.object({
    body: zAuthSignInPayload,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Auth sign in
 */
export const zSignInHandlerResponse = zAuthSignInResponse;

export const zSignUpHandlerData = z.object({
    body: zAuthSignUpPayload,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Auth sign up
 */
export const zSignUpHandlerResponse = zAuthSignUpResponse;

export const zBreedsListHandlerData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * List of all cat breeds
 */
export const zBreedsListHandlerResponse = zBreedsListResponse;

export const zCatDetailHandlerData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Details for a specific cat
 */
export const zCatDetailHandlerResponse = zCatDetailResponse;

export const zMatchesListHandlerData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * List of all matches for a specific cat
 */
export const zMatchesListHandlerResponse = zMatchesListResponse;

export const zMatchAddUpdateHandlerData = z.object({
    body: zMatchAddRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Match created
 */
export const zMatchAddUpdateHandlerResponse = zMatchAddedResponse;

export const zMatchSuggestionsHandlerData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * List of match suggestions for a specific cat
 */
export const zMatchSuggestionsHandlerResponse = zMatchSuggestionsResponse;

export const zSessionGetFromCookieHandlerData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Session for current user
 */
export const zSessionGetFromCookieHandlerResponse = zCatDetailResponse;
