photo_upload_dir = "ui/src/public/images/cats"

[testUsers]
adminUsername = "admin-user"
adminPassword = "admin-user-password"
unprivilegedUsername = "unprivileged-user"
unprivilegedPassword = "unprivileged-user-password"
