# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  dev:
    desc: Run the API server with debug logging and restart on changes
    cmds:
      - RUST_LOG=meow_mingle=debug,axum=debug,tower_http=debug cargo watch -c -w src -x check -x run

  cov:
    desc: Run test coverage
    cmds:
      - cargo llvm-cov --all-targets nextest --color always

  covhtml:
    desc: Run test coverage and open HTML report
    cmds:
      - cargo llvm-cov --all-targets nextest --html --open

  genapi:
    desc: Generate API
    cmds:
      - cmd: cargo p
        ignore_error: true
      - powershell -ExecutionPolicy Bypass -File scripts/fetch-openapi.ps1
      - echo "Generating TypeScript client..."
      - powershell -Command "Set-Location ui/src; npx @hey-api/openapi-ts"
      - echo "Done!"
