// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { breedsListHandler, catDetailHandler, matchAddUpdateHandler, matchesListHandler, matchSuggestionsHandler, type Options, sessionGetFromCookieHandler, signInHandler, signUpHandler } from '../sdk.gen';
import type { BreedsListHandlerData, BreedsListHandlerResponse, CatDetailHandlerData, CatDetailHandlerResponse, MatchAddUpdateHandlerData, MatchAddUpdateHandlerResponse, MatchesListHandlerData, MatchesListHandlerResponse, MatchSuggestionsHandlerData, MatchSuggestionsHandlerResponse, SessionGetFromCookieHandlerData, SessionGetFromCookieHandlerResponse, SignInHandlerData, SignInHandlerError, SignInHandlerResponse, SignUpHandlerData, SignUpHandlerResponse } from '../types.gen';

export const signInHandlerMutation = (options?: Partial<Options<SignInHandlerData>>): UseMutationOptions<SignInHandlerResponse, SignInHandlerError, Options<SignInHandlerData>> => {
    const mutationOptions: UseMutationOptions<SignInHandlerResponse, SignInHandlerError, Options<SignInHandlerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await signInHandler({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const signUpHandlerMutation = (options?: Partial<Options<SignUpHandlerData>>): UseMutationOptions<SignUpHandlerResponse, DefaultError, Options<SignUpHandlerData>> => {
    const mutationOptions: UseMutationOptions<SignUpHandlerResponse, DefaultError, Options<SignUpHandlerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await signUpHandler({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const breedsListHandlerQueryKey = (options?: Options<BreedsListHandlerData>) => createQueryKey('breedsListHandler', options);

export const breedsListHandlerOptions = (options?: Options<BreedsListHandlerData>) => queryOptions<BreedsListHandlerResponse, DefaultError, BreedsListHandlerResponse, ReturnType<typeof breedsListHandlerQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await breedsListHandler({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: breedsListHandlerQueryKey(options)
});

export const catDetailHandlerQueryKey = (options: Options<CatDetailHandlerData>) => createQueryKey('catDetailHandler', options);

export const catDetailHandlerOptions = (options: Options<CatDetailHandlerData>) => queryOptions<CatDetailHandlerResponse, DefaultError, CatDetailHandlerResponse, ReturnType<typeof catDetailHandlerQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await catDetailHandler({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: catDetailHandlerQueryKey(options)
});

export const matchesListHandlerQueryKey = (options?: Options<MatchesListHandlerData>) => createQueryKey('matchesListHandler', options);

export const matchesListHandlerOptions = (options?: Options<MatchesListHandlerData>) => queryOptions<MatchesListHandlerResponse, DefaultError, MatchesListHandlerResponse, ReturnType<typeof matchesListHandlerQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await matchesListHandler({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: matchesListHandlerQueryKey(options)
});

export const matchAddUpdateHandlerMutation = (options?: Partial<Options<MatchAddUpdateHandlerData>>): UseMutationOptions<MatchAddUpdateHandlerResponse, DefaultError, Options<MatchAddUpdateHandlerData>> => {
    const mutationOptions: UseMutationOptions<MatchAddUpdateHandlerResponse, DefaultError, Options<MatchAddUpdateHandlerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await matchAddUpdateHandler({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const matchSuggestionsHandlerQueryKey = (options?: Options<MatchSuggestionsHandlerData>) => createQueryKey('matchSuggestionsHandler', options);

export const matchSuggestionsHandlerOptions = (options?: Options<MatchSuggestionsHandlerData>) => queryOptions<MatchSuggestionsHandlerResponse, DefaultError, MatchSuggestionsHandlerResponse, ReturnType<typeof matchSuggestionsHandlerQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await matchSuggestionsHandler({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: matchSuggestionsHandlerQueryKey(options)
});

export const sessionGetFromCookieHandlerQueryKey = (options?: Options<SessionGetFromCookieHandlerData>) => createQueryKey('sessionGetFromCookieHandler', options);

export const sessionGetFromCookieHandlerOptions = (options?: Options<SessionGetFromCookieHandlerData>) => queryOptions<SessionGetFromCookieHandlerResponse, DefaultError, SessionGetFromCookieHandlerResponse, ReturnType<typeof sessionGetFromCookieHandlerQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await sessionGetFromCookieHandler({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: sessionGetFromCookieHandlerQueryKey(options)
});
